version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: x86
      CXX_FLAGS: ""
      LINKER_FLAGS: ""
      GENERATOR: Visual Studio 14 2015

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      CXX_FLAGS: ""
      LINKER_FLAGS: ""
      GENERATOR: Visual Studio 15 2017

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: x64
      CXX_FLAGS: ""
      LINKER_FLAGS: ""
      GENERATOR: Visual Studio 14 2015 Win64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      CXX_FLAGS: ""
      LINKER_FLAGS: ""
      GENERATOR: Visual Studio 15 2017 Win64

init:
  - cmake --version
  - msbuild /version

before_build:
  - cmake . -G "%GENERATOR%" -DPROFILING_TIMERS_ENABLE_TESTS=ON -DCMAKE_CXX_FLAGS="%CXX_FLAGS%" -DCMAKE_EXE_LINKER_FLAGS="%LINKER_FLAGS%" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"

build_script:
  - cmake --build . --config Release

test_script:
  - Release\profiling_timers_test.exe
